name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: examples
      run: bin/threads && bin/actors && bin/async-await && bin/generators && bin/rollback-state
    - name: tests
      run: bin/test/traits

      
